### ISSUE TITLE
How to use new version of "react-router-dom": "^6.3.0"

### ISSUE THREAD

**Issue by chirag-logical** [chirag-logical/local_skill_admin#6]
Instead of each of them having their own Switch, they instead are just arrays of Routes. So when you add them to the Switch tag you already have, you are just extending the number of routes to include those from userRoutes and masterRoutes.

**Comment by chiragmehta900** [comment]
`const Component = () => {
  const { id } = useParams();

  return <h1>Id: {id}</h1>;
};

export default function App() {
  return (
    <div className="App">
      <Link to="/home/user/123/friends/456">Test?</Link>

      <Routes>
        <Route path="home/user/:id/friends/:id" element={<Component />} />
      </Routes>
    </div>
  );
}`

This is how to can use "react-router-dom": "^6.3.0" new version.
